### ISSUE TITLE
Migrations do not load any RW/ RT boundaries

### ISSUE THREAD

**Issue by timlinux** [kartoza/jakarta-flood-maps#18]
![selection_001](https://cloud.githubusercontent.com/assets/178003/5677578/2defac26-97f1-11e4-9acb-a0b9746eaa28.png)

When loading the database using migrations, I don't get any RW/RT boundaries. See image above.

**Comment by cchristelis** [comment]
Hi @timlinux 
The models and migrations have been changed in a way that is incompatible with old versions of the database. You will need to drop these tables and re-generate them from scratch.
migrate flood_mapper zero --fake
and drop all flood_mapper tables (they match flood_mapper_*).
then re-run the migrations 
migrate flood_mapper

**Comment by cchristelis** [comment]
It turns out this has nothing to do with the migrations there is a typo causing:
 GET http://localhost:8000/api/locale/58/?format=json 404 (NOT FOUND)

**Comment by cchristelis** [comment]
bug fixed and merged into develop.
